using DiagramMaker.Domain;

namespace DiagramMaker.Services;

public sealed partial class InternalLlmClient
{
    private static bool Contains(SourceSpan owner, SourceSpan? child) => child is not null && owner.FilePath == child.FilePath &&
        owner.RevisionSha == child.RevisionSha && child.StartLine >= owner.StartLine && child.EndLine <= owner.EndLine &&
        (owner.StartOffset is null || child.StartOffset is null || child.StartOffset >= owner.StartOffset) &&
        (owner.EndOffset is null || child.EndOffset is null || child.EndOffset <= owner.EndOffset);

    // The syntax tree owns structure. These groups are never generated by the LLM
    // and do not assert semantic review. Only the common annotations are reviewed.
    internal static IReadOnlyList<ExecutionMeaningResult> BuildExecutionMeanings(IReadOnlyList<ExecutionMeaningInput> inputs) =>
        inputs.Select(input =>
        {
            var units = new List<ExecutionMeaningUnit>();
            void Group(IReadOnlyList<ExecutionFact> region)
            {
                for (var i = 0; i < region.Count; i++)
                {
                    var fact = region[i];
                    var ids = new List<string> { fact.Id };
                    if (fact.Kind is "declare" or "assign" && fact.Evaluation.Count == 0)
                        while (i + 1 < region.Count && ids.Count < 32 && region[i + 1].Kind is "declare" or "assign" &&
                            region[i + 1].Evaluation.Count == 0 && region[i + 1].Children.Count == 0 && region[i + 1].Alternative.Count == 0)
                            ids.Add(region[++i].Id);
                    units.Add(new("코드의 관측 동작", "구문 분석으로 확정한 실행 영역입니다. 의미 설명은 공유 단위에서 검토합니다.", ids));
                    Group(fact.Evaluation); Group(fact.Children); Group(fact.Alternative);
                }
            }
            Group(input.Events);
            var plan = new ExecutionMeaningPlan("구문 분석으로 확정한 실행 구조", "implementation",
                ExecutionMeaningValidation.Steps(input.Events), units);
            return new ExecutionMeaningResult(input, plan, null);
        }).ToArray();

    private static SharedDiagramGroup ApplyExecutionStatus(SharedDiagramGroup group, IReadOnlyList<ExecutionMeaningResult> meanings,
        IReadOnlyList<SourceFact> facts) => group with { Pages = group.Pages.ToDictionary(pair => pair.Key, pair =>
        {
            var page = pair.Value;
            var ids = page.Diagram.Nodes.SelectMany(n => n.SourceFactIds ?? []).Concat(page.Diagram.Edges.SelectMany(e => e.SourceFactIds ?? [])).ToHashSet();
            var spans = facts.Where(f => ids.Contains(f.Id)).Select(f => f.Span).ToArray();
            var relevant = meanings.Where(m => spans.Any(s => Contains(m.Input.Span, s))).ToArray();
            var unsupported = relevant.Any(m => ExecutionSequenceProjection.Flatten(m.Input.Events).Any(e => e.Kind == "unsupported"));
            var warnings = unsupported ? page.Warnings.Append("일부 제어 구문의 실행 경로는 정적으로 확정하지 못했습니다. 해당 범위의 원문 근거를 확인하세요.").Distinct().ToArray() : page.Warnings;
            return page with
            {
                Status = unsupported ? "Incomplete" : page.Status,
                FailureStage = unsupported ? "execution-structure" : page.FailureStage,
                Warnings = warnings,
                Diagram = page.Diagram with { Provenance = page.Diagram.Provenance.Concat([ExecutionMeaningValidation.Version, "syntax-owned-execution"]).Distinct().ToArray() },
                Explanation = page.Explanation is null ? null : page.Explanation with { Warnings = warnings,
                    Status = unsupported ? "Incomplete" : page.Explanation.Status, Basis = "SyntaxAndReviewedAnnotations" }
            };
        }) };
}
